### ISSUE TITLE
feat: allow CMS to modify static text

### ISSUE THREAD

**Issue by hollandjg** [thepolicylab-projectportals/project-portal-theme#373]
Parts:
- [x] use Page templates rather than .js files and save each page as a normal JSON file 
  - [x] card pages (open, ongoing, completed) #414
    - [x]  fix: broken image on index page #421 
  - [x] about page #415 
  - [x] contact & thank you pages #416 
- [x] Split up the input language file but put it back together in the same "staticText" object in GraphQL
  - [x] Site Metadata #417 
  - [x] Navbar #418 
  - [x] BottomBanner  #418 
  - [x] Footer  #418 
  - [x] mainContactText  #418 
  - [x] projectInterestLink  #418 
- [x] Images #421 
- [x] Roll out
  - [x] NC https://github.com/thepolicylab-projectportals/nc-content/pull/176
  - [x] SATX https://github.com/thepolicylab-projectportals/satx-content/pull/93
  - [x] Federal Preview

Out of scope (create new issues):
- Tailwind config
- ReCaptcha key
- Previews
- refactor: Navbar title box to allow a zero length title which is different from the site metadata
